# Docker Compose configuration for the Go-Redis application

services: 
  app:
    build:
      context: ./app # Path to the build context
      dockerfile: Dockerfile # Dockerfile to use for building the image
    container_name: go-redis-app # Name of the container
    networks:
      - innernet # Network to which the container will be connected
    ports:
      - "0:7001" # Port mapping for the container
    environment:
      #- REDIS_URL=redis:6001  # Environment variable for Redis URL (commented out)
      - REDIS_URL=redis:6379 # Environment variable for Redis URL
    depends_on:
      - redis # Dependency on the Redis service
    restart: unless-stopped # Restart policy for the container
    logging:
      driver: "json-file" # Logging driver to use
      options:
        max-size: "10m" # Maximum size of the log file
        max-file: "10" # Maximum number of log files to retain

  redis:
    image: redis:alpine # Redis image to use
    container_name: go-redis # Name of the container
    networks:
      - innernet # Network to which the container will be connected
    ports:
      - "6379:6379" # Port mapping for the container
    volumes:
      - redis-data:/data # Volume to persist Redis data
    restart: unless-stopped # Restart policy for the container
    logging:
      driver: "json-file" # Logging driver to use
      options:
        max-size: "10m" # Maximum size of the log file
        max-file: "10" # Maximum number of log files to retain



volumes:
  redis-data:
    name: go-redis # Name of the volume

networks:
  innernet:
    driver: bridge # Network driver to use
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true" # Enable IP masquerading
      com.docker.network.bridge.enable_icc: "true" # Enable inter-container communication
      com.docker.network.driver.mtu: "1500" # Set the MTU for the network
      com.docker.network.bridge.name: "${BRIDGE_NAME}" # Name of the bridge
    name: "${NET_NAME}" # Name of the network
    ipam:
      driver: default # IPAM driver to use
      config:
        - subnet: 10.1.${NET_ID}.0/24 # Subnet configuration for the network

