  app:
    build:
      context: ./app # Path to the build context
      dockerfile: Dockerfile # Dockerfile to use for building the image
    container_name: go-redis-app # Name of the container
    networks:
      - innernet # Network to which the container will be connected
    ports:
      - "0:7001" # Port mapping for the container
    environment:
      #- REDIS_URL=redis:6001  # Environment variable for Redis URL (commented out)
      - REDIS_URL=redis:6379 # Environment variable for Redis URL
    depends_on:
      - redis # Dependency on the Redis service
    restart: unless-stopped # Restart policy for the container
    logging:
      driver: "json-file" # Logging driver to use
      options:
        max-size: "10m" # Maximum size of the log file
        max-file: "10" # Maximum number of log files to retain